# Generated by Django 6.1.1 on 2026-10-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Original uploaded file (empty when the resume was pasted).', upload_to='resumes/%Y/%m/')),
                ('text', models.TextField(help_text='Extracted resume text used for analysis.')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(blank=True)),
                ('job_description', models.TextField(blank=True, help_text='Job description fetched from the link or pasted by the user.')),
                ('mode', models.CharField(choices=[('GENERAL', 'General'), ('JOB_MATCH', 'Job Match')], default='GENERAL', max_length=20)),
                ('overall_score', models.PositiveSmallIntegerField(help_text='0-100 score shown in history and dashboards.')),
                ('semantic_similarity', models.FloatField(blank=True, help_text='Cosine similarity between resume and JD embeddings (0-1).', null=True)),
                ('result', models.JSONField(default=dict, help_text='Full structured AI response (categories, keywords, etc.).')),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_analyses', to='applications.jobapplication')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resume', '-created_at'], name='resumes_res_resume__5b9f99_idx')],
            },
        ),
    ]
