# Generated by Django 6.1.1 on 2026-09-18 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=100)),
                ('interview_type', models.CharField(choices=[('ONLINE', 'Online'), ('PHONE', 'Phone'), ('IN_PERSON', 'In Person')], default='ONLINE', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication')),
            ],
        ),
    ]
